# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4703cb48b8ee465a055e2bf7350bc281b420d2526fafe345f83742d658ab72bda0e0bf26711fa2a50565eea1cd63ce9d76768638ac2bc7d10e6470dfe37eb05a

test:
  secret_key_base: 72c0182302b8a4f1c44a17451c3e4850798ca6ca1a7451e25afb9e3eb7a3be486624d4e2ef8450e5275da84d9f79f08fd28a95614b03ea4fa11218edc2aa0ac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
